aliases:
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ arch }}-{{ checksum "package.json" }}
      - v1-yarn-{{ arch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ arch }}-{{ checksum "package.json" }}

  - &yarn
    |
      yarn

defaults: &defaults
  docker:
    - image: circleci/node:8.10.0
  working_directory: ~/repo

version: 2
jobs:

  checkout:
    <<: *defaults
    steps:
      - checkout

      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

      - persist_to_workspace:
          root: .
          paths: .
  
  unit-test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Lint
          command: yarn lint

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Now CLI
          command: yarn global add now@canary
      - deploy:
          name: Deploy & Alias
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              NOW_URL=$(now --token $ZEIT_TOKEN --team $ZEIT_TEAM --local-config now.json)
              echo "NOW_URL" $NOW_URL
              NOW_ALIAS=$(jq -r '.alias[0]' now.json)
              echo "NOW_ALIAS" $NOW_ALIAS
              now --token $ZEIT_TOKEN --team $ZEIT_TEAM alias set $NOW_URL $NOW_ALIAS
            else
              echo "Not master branch! cancel deploy!"
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - unit-test:
          requires:
            - checkout
      - deploy:
          requires:
            - unit-test
